### ISSUE TITLE
Implict flow not supported

### ISSUE THREAD

**Issue by georgeboot** [ronvanderheijden/openid-connect#12]
Issue previously raised in https://github.com/thephpleague/oauth2-server/issues/1374

When I use the authorisation code grant, this works as expected.

However, when I try to do an implict flow by setting `response_type=token id_token` or `response_type=id_token`, the server always rejects the request because the following check does not match the request:
https://github.com/thephpleague/oauth2-server/blob/ab7714d073844497fd222d5d0a217629089936bc/src/Grant/ImplicitGrant.php#L105-L109

Are there any recommended ways to bypass this issue?

I am using Laravel Passport.

**Comment by ronvanderheijden** [comment]
It is not recommended to use the implicit flow (and some servers prohibit this flow entirely) due to the inherent risks of returning access tokens in an HTTP redirect without any confirmation that it has been received by the client.

In other words, **the Implicit Flow is Legacy** and not supported.
