### ISSUE TITLE
HTTP scheme not available in IdTokenResponse

### ISSUE THREAD

**Issue by deviationist** [ronvanderheijden/openid-connect#13]
The HTTPS-schema is hard coded here: https://github.com/ronvanderheijden/openid-connect/blob/cd4b1e4a57076d12d65212e228b413f282fb6b2d/src/IdTokenResponse.php#L44

It would be very useful to use HTTP-scehma during local development and testing. Is it possibly to make it configurable?

I've been using it together with Laravel Passport, and since the Issuer is always set to "https://localhost:8000" I get an error in the client that's trying to validate the Id Token, since it tries to match it with the client with URL "http://localhost:8000".

**Comment by moufmouf** [comment]
:+1: on this.

I have the same issue.

The problem is that the `IdTokenResponse` should be framework agnostic. My gut feeling is that the whole "protocol + host" should be fetched from the PSR7 request object (otherwise, this code cannot work in frameworks like Octane or Swoole that won't have a `$_SERVER['HTTP_HOST']`.

This issue is that the request is not available at this point in the code...

**Comment by moufmouf** [comment]
@deviationist I just opened a pull request to make the HTTP scheme (and whole issuer) configurable => #15
